### ISSUE TITLE
No module named 'designSeq'

### ISSUE THREAD

**Issue by naoto0804** [PKU-ICST-MIPL/PosterLayout-CVPR2023#12]
When I try `sh test_n_eval.sh`, the following error occurred. It seems that `designSeq` is missing. Any plan to include `designSeq`?
```
Inference is started.
Traceback (most recent call last):
  File "infer.py", line 12, in <module>
    from dataloader import canvas
  File "/Users/s13579/Documents/codes/PosterLayout-CVPR2023/dataloader.py", line 16, in <module>
    from designSeq import reorder
ModuleNotFoundError: No module named 'designSeq'
```

**Comment by theKinsley** [comment]
Hello Naoto, thank you for your patience. We've released all codes required for training, including ```designSeq.py```. Hope this will be helpful to your work!

**Comment by naoto0804** [comment]
I'll look into it, thanks!
