### ISSUE TITLE
train_csv_9973.csv文件

### ISSUE THREAD

**Issue by Du-Yao** [PKU-ICST-MIPL/PosterLayout-CVPR2023#18]
您好，感谢您和团队的贡献，请问train_csv_9973.csv要怎么获取呢？

**Comment by shineYuSong** [comment]
> 您好，感谢您和团队的贡献，请问train_csv_9973.csv要怎么获取呢？

have you finished?

**Comment by Du-Yao** [comment]
是的，已经申请通过拿到数据了，谢谢。

2023年11月7日 21:36，shineYuSong ***@***.******@***.***>> 写道：



您好，感谢您和团队的贡献，请问train_csv_9973.csv要怎么获取呢？

have you finished?

**Comment by Amber0913** [comment]
您好，请问这个train_csv_9973.csv文件该怎么申请呢？
