### ISSUE TITLE
How to download the dataset

### ISSUE THREAD

**Issue by yingying1012** [PKU-ICST-MIPL/PosterLayout-CVPR2023#28]
Hello, the online storage on the dataset download page is empty. Where can I get the dataset

**Comment by Steven-xzr** [comment]
Hi @yingying1012 , do you know how to download the dataset? Thank you!

**Comment by yingying1012** [comment]
Hello, the dataset can be downloaded from the provided page: project page. The annotation information needs to be submitted for application, and the author will send it to you via email.




lollipop
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PKU-ICST-MIPL/PosterLayout-CVPR2023"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月16日(星期二) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PKU-ICST-MIPL/PosterLayout-CVPR2023] How to download the dataset (Issue #28)





 
Hi @yingying1012 , do you know how to download the dataset? Thank you!

**Comment by Steven-xzr** [comment]
Thank you @yingying1012 !
